# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project
  pod 'Alamofire', '~> 5.8'
  pod 'SCLAlertView', '~> 0.8'
  pod 'SDWebImage', '~> 5.0'
  pod 'ProgressHUD', '~> 13.8.6'
  pod 'ImageSlideshow', '~> 1.9'
  pod "ImageSlideshow/SDWebImage", '~> 1.9'

end
